export const ALREADY_AT_HOME: string = '欢迎使用金融计算器！';
export const ZERO_DIVISION_ERROR: string = '真的除不尽啊！';
export const ALREADY_AT_CALCULATOR: string = '开始计算吧！';
export const ALREADY_AT_MANUAL: string = '这里就是使用指南！';
export const UNKNOWN_OPTION: string = '未知选项';
export const NO_DELETING: string = '数据已删完，我无处可下手啦！';
export const NO_CLEAR: string = '俺也一样！';
export const IRR_REQUIREMENT_ERROR: string = '要计算IRR，现金流至少有一正一负';
export const IRR_CONVERGENCE_ERROR: string = 'IRR计算不收敛';
export const BAD_REQUEST: string = '请求失败';
export const INF_ERROR: string = '计算结果为无穷大';
export const COMPLEX_ERROR: string = '计算结果是复数，不能处理';
export const TAN_ERROR: string = 'tan 函数在 π/2 的倍数处未定义';
export const TAN_ANGLE_ERROR: string = 'tan 函数在 90° 的倍数处未定义';
export const LOG_ERROR: string = '不能对非正数求对数！';
export const NO_MORE_CLICK: string = '不要重复计算哦'